language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  include:
    - name: "Python on Xenial Linux"
      os: linux
      dist: xenial
    - name: "Python on MacOS"
      os: osx
      osx_image: xcode10.2
      language: shell
    - name: "Code analyze"
      python: 3.7
      os: linux
      addons:
        sonarcloud:
          organization: "brobots-team"
      script: sonar-scanner

script: python -m unittest tests/test_checkArgs.py

notifications:
  email:
    on_failure: always
    on_error: always