language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

dist: trusty

addons:
  sonarcloud:
    organization: "mwixbot" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN


script: 
  - python -m unittest tests/test_checkArgs.py
  - sonar-scanner