language: python

dist: trusty

python:
  - "3.5"
  - "3.6"
  - "3.7"

os:
  - linux
  - osx

script: python -m unittest tests/test_checkArgs.py

addons:
  sonarcloud:
    organization: "brobots-team"

jobs:
  include:
    - stage: "Code analyze"
      script: sonar-scanner
      python: 3.7
      os: linux

notifications:
  email:
    on_failure: always
    on_error: always