language: python

dist: trusty

addons:
  sonarcloud:
    organization: "brobots-team"

jobs:
  include:
    - stage: test
      name: "Unit tests"
      script: python -m unittest tests/test_checkArgs.py
    - stage: checkcode
      name: "Code analyze"
      script: sonar-scanner

notifications:
  email: false