language: python

dist: xenial

python:
  - '3.5'
  - '3.6'
  - '3.7'

before_script: tests/init_structure.sh
script: python -m unittest tests/test_objects_sonar.py

jobs:
  include:
    - stage: "Code analyze"
      python: 3.7
      addons:
        sonarcloud:
          organization: "brobots-team"
      before_script: echo "Пропуск разворачивания тестовой структуру"
      script: sonar-scanner

notifications:
  email:
    on_failure: change
    on_error: change