language: python

dist: xenial

python:
  - '3.5'
  - '3.6'
  - '3.7'

script: python -m unittest tests/test_checkArgs.py

jobs:
  include:
    - stage: "Code analyze"
      python: 3.7
      addons:
        sonarcloud:
          organization: "brobots-team"
      script: sonar-scanner

notifications:
  email:
    on_failure: change
    on_error: change